### ISSUE TITLE
i18nFind breaking in 1.2?

### ISSUE THREAD

**Issue by leefisher** [TAPevents/tap-i18n-db#19]
After upgrading to 1.2 we are getting the null or undefined error.  Changing to find works.
Is there an issue with seeing the project-tap.i18n file or a router issue?

20150922-14:48:32.070(2)? Exception from sub applications id NbWxw3dTZANwGWXnP TypeError: Array.prototype.indexOf called on null or undefined
20150922-14:48:32.070(2)?     at [object Object].obj.i18nFind (packages/tap_i18n-db/packages/tap_i18n-db.js:352:1)
20150922-14:48:32.070(2)?     at indexOf (native)
20150922-14:48:32.071(2)?     at [object Object].i18n_handler [as _handler](packages/tap_i18n-db/packages/tap_i18n-db.js:429:1)
20150922-14:48:32.072(2)?     at [object Object]._.extend._startSubscription (livedata_server.js:842:9)
20150922-14:48:32.072(2)?     at [object Object]._.extend.protocol_handlers.sub (livedata_server.js:614:12)
20150922-14:48:32.071(2)?     at [object Object]._.extend._runHandler (livedata_server.js:1023:17)
20150922-14:48:32.072(2)?     at livedata_server.js:548:43
20150922-14:48:32.071(2)?     at maybeAuditArgumentChecks (livedata_server.js:1692:12)
20150922-14:48:32.071(2)?     at [object Object].Meteor.publish.query

**Comment by timbrandin** [comment]
Adding `TAPi18n.conf.supported_languages = ['en', 'sv'];` – solved the issue for us.

Would be good if TAPi18n was better at picking up the supported languages, or more failing gracefully.
